global:
  scrape_interval: 5s
  
scrape_configs:

- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
   - targets: ['localhost:9090']
   
- job_name: Model-unit-tests
  metrics_path: actuator/prometheus
  scrape_interval: 5s
  static_configs:
   - targets: ['host.docker.internal:8080']
